### ISSUE TITLE
Specific Icon sets are not included in Weather Underground Icons

### ISSUE THREAD

**Issue by KangboLu** [dvcoders/16sp-yql-weather#2]
![breezy](https://cloud.githubusercontent.com/assets/17485959/14938328/e2ebc870-0ed4-11e6-99e0-74f8a8dabe48.png)
![mostly clear](https://cloud.githubusercontent.com/assets/17485959/14938330/e2ec80e4-0ed4-11e6-8ab5-e71d48c4a7d9.png)
![scattered showers](https://cloud.githubusercontent.com/assets/17485959/14938331/e2ece78c-0ed4-11e6-8974-97a4003e1c8b.png)
![scattered thunderstorms](https://cloud.githubusercontent.com/assets/17485959/14938329/e2ec65c8-0ed4-11e6-9c9b-c5ebd53799a5.png)
![showers](https://cloud.githubusercontent.com/assets/17485959/14938333/e2edf686-0ed4-11e6-9f24-ef62778c3527.png)
![windy](https://cloud.githubusercontent.com/assets/17485959/14938332/e2ece5c0-0ed4-11e6-86cd-9fe605809cdd.png)

**Comment by jryio** [comment]
@janka102 Actually knows about this one ;) 
Something wrong with the icon CDN?

**Comment by KangboLu** [comment]
The responds from YQL for the condition do not match the icon in the Weather Underground Icon Sets. There is no "showers" in the icon sets from the Weather Underground website

**Comment by KangboLu** [comment]
There is no "showers" in the icon sets

**Comment by janka102** [comment]
Yeah that's exactly it. If you notice, I have a little thing to get Thunder Showers working. But it's definitely not perfect. I tried to get the Yahoo icons, but those didn't really have a pattern IIRC

**Comment by janka102** [comment]
I was able to get the Yahoo icons to work in d0b8aac
